[package]
name    = "rspgod"
version = "0.1.0"
authors = ["Michael Baker <michaeltbaker@gmail.com>"]

[lib]
name       = "rspgod"
crate-type = ["staticlib"]

[dependencies.libc]
version = "0.1.*"

[dependencies.rustc-serialize]
version = "0.3.14"

[dependencies]
postgres = "0.9"