[package]
name    = "rspgod"
version = "0.1.0"
authors = ["Michael Baker <michaeltbaker@gmail.com>"]

[lib]
name       = "rspgod"
crate-type = ["staticlib"]

[dependencies.bindgen]
git = "https://github.com/crabtw/rust-bindgen.git"

[dependencies.libc]
version = "0.1.*"
